### ISSUE TITLE
I can't change name of class

### ISSUE THREAD

**Issue by Numpek2k** [markhughes/flight-skeleton#1]
Hi i have got some problems ,when i tried to change name of class in Demo.php it's stop working. Pls help me!! (to be honest when i change name of class in Demo.php i also changed the path in routes.php)

**Comment by markhughes** [comment]
What error shows up?

**Comment by Numpek2k** [comment]
@MarkehMe 
![image](https://user-images.githubusercontent.com/33579708/32698809-a7a12d14-c7ab-11e7-9799-63a6c8d7bdc8.png)

**Comment by Numpek2k** [comment]
@MarkehMe  So what you think about this ?

**Comment by Numpek2k** [comment]
@MarkehMe For some reasons name of class in Demo.php must be the same as file name ... When i change the name of Demo.php(for example to Start.php) and next changed the name of class (for example to Start) it's start working but its kinda weird for  me .

**Comment by markhughes** [comment]
Did you manage to get it working? 😄

**Comment by Numpek2k** [comment]
Yea its ok right now
